#!/bin/bash
set -euo pipefail

un="$(uname)"
local_os="linux"
if [ ${un} == 'Darwin' ]; then
    local_os="darwin"
fi

# Render assets
if [ ! -d "cluster" ]; then
  ../../_output/bin/${local_os}/bootkube render --asset-dir=cluster --api-servers=https://172.17.4.100:443
  # Add rendered kubeconfig to the node user-data
  cat user-data.sample > cluster/user-data && sed 's/^/      /' cluster/auth/kubeconfig >> cluster/user-data
fi

# Start the VM
vagrant up
vagrant ssh-config > ssh_config

# Copy locally rendered assets to the server
scp -q -F ssh_config -r cluster core@default:/home/core/cluster
scp -q -F ssh_config ../../_output/bin/linux/bootkube core@default:/home/core

# Run bootkube
ssh -q -F ssh_config core@default "sudo /home/core/bootkube start --asset-dir=/home/core/cluster 2>> /home/core/bootkube.log"

echo
echo "Bootstrap complete. Access your kubernetes cluster using:"
echo "kubectl --kubeconfig=cluster/auth/kubeconfig get nodes"
echo
