apiVersion: v1
kind: Pod
metadata:
  name: pod-checkpointer
  namespace: kube-system
  labels:
    k8s-app: pod-checkpointer
spec:
  containers:
  - name: checkpoint
    image: {{ REPO }}:{{ TAG }}
    command:
    - /checkpoint
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
    - mountPath: /srv/kubernetes
      name: srv-kubernetes
  hostNetwork: true
  restartPolicy: Always
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: srv-kubernetes
    hostPath:
      path: /srv/kubernetes
