#!/bin/bash

source ./config-env

echo "rendering manifests to ${OUTDIR}"
../../bin/bootkube render \
	--outdir=${OUTDIR} \
	--apiserver-cert-ip-addrs=${APISERVER_CERT_IPS} \
	--etcd-servers=${ETCD_SERVERS} \
	--api-servers=${API_SERVERS}

echo "inserting kubeconfig into user-data"
cat user-data.sample > cluster/user-data && sed 's/^/      /' cluster/auth/kubeconfig.yaml >> cluster/user-data
cp cluster/user-data{,-worker}
cp cluster/user-data{,-controller}
sed -i.bak \
    -e 's/127\.0\.0\.1/172.17.4.101/' \
    -e '/^.*master.*/d' \
    cluster/user-data-worker
