#!/bin/bash

# dependencies
#   jq
#   docker
#   journalctl

set -euo pipefail

LOGS_DIR=${LOGS_DIR:-logs}

rm -rf ${LOGS_DIR} && mkdir -p ${LOGS_DIR}

echo Capturing Docker Logs
for CID in $( docker ps -a -q ); do
  data=$(docker inspect $CID) || true
  [ -z "$data" ] && continue
  if [ "$(echo "$data" | jq '.[0].Path')" == "\"/pause\"" ]; then
    # Ignore pause pods
    continue
  fi

  NAME=$(echo "$data" | jq '.[0].Name' -r | sed 's/^\/k8s_//g')
  FILENAME=${LOGS_DIR}/containers/$NAME.log
  mkdir -p $(dirname $FILENAME)
  echo "Generating Log for ${NAME} at ${FILENAME}"
  docker logs -t $CID &> $FILENAME || true
done

echo Capturing Systemd Logs
for UNIT in kubelet docker; do
  filename=${LOGS_DIR}/services/$UNIT.log
  mkdir -p $(dirname $filename)
  journalctl -o short-iso --no-hostname -u $UNIT &> $filename
done

echo DONE
